# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/edt/RNG/RNG.srcs/sources_1/ip/clk_200_to_100/clk_200_to_100.xci
# IP: The module: 'clk_200_to_100' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/edt/RNG/RNG.gen/sources_1/ip/clk_200_to_100/clk_200_to_100_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_200_to_100'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/edt/RNG/RNG.gen/sources_1/ip/clk_200_to_100/clk_200_to_100.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_200_to_100'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/edt/RNG/RNG.gen/sources_1/ip/clk_200_to_100/clk_200_to_100_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_200_to_100'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/edt/RNG/RNG.srcs/sources_1/ip/clk_200_to_100/clk_200_to_100.xci
# IP: The module: 'clk_200_to_100' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/edt/RNG/RNG.gen/sources_1/ip/clk_200_to_100/clk_200_to_100_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_200_to_100'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/edt/RNG/RNG.gen/sources_1/ip/clk_200_to_100/clk_200_to_100.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_200_to_100'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/edt/RNG/RNG.gen/sources_1/ip/clk_200_to_100/clk_200_to_100_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_200_to_100'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
