set_property SRC_FILE_INFO {cfile:C:/Entrust/fwmuro/muro.xdc rfile:../../../../../Entrust/fwmuro/muro.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG14     [get_ports o_random_bit]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF13     [get_ports o_raw_sample_capture_led]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E13     [get_ports o_uart_tx]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFGCE_X0Y73  [get_cells -regexp -hier ".*ring_gen.0..ring_bufg" ]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFGCE_X0Y72  [get_cells -regexp -hier ".*ring_gen.1..ring_bufg" ]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X95Y185    [get_cells -regexp -hier ".*ring_stage.0._inferred_i_1" ]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X95Y185    [get_cells -regexp -hier ".*ring_stage.0._inferred_i_2" ]
set_property src_info {type:XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X95Y185    [get_cells -regexp -hier ".*ring_stage.0._inferred_i_3" ]
set_property src_info {type:XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X95Y185    [get_cells -regexp -hier ".*ring_stage.0._inferred_i_4" ]
set_property src_info {type:XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X95Y185    [get_cells -regexp -hier ".*ring_stage.0._inferred_i_5" ]
set_property src_info {type:XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X95Y185    [get_cells -regexp -hier ".*ring_stage.0._inferred_i_6" ]
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X95Y185    [get_cells -regexp -hier ".*ring_stage.0._inferred_i_7" ]
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X95Y185    [get_cells -regexp -hier ".*ring_stage.0._inferred_i_8" ]
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X96Y185    [get_cells -regexp -hier ".*ring_stage.0._inferred_i_9" ]
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X96Y185    [get_cells -regexp -hier ".*ring_stage.0._inferred_i_10" ]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X96Y185    [get_cells -regexp -hier ".*ring_stage.0._inferred_i_11" ]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X96Y185    [get_cells -regexp -hier ".*ring_stage.0._inferred_i_12" ]
set_property src_info {type:XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X96Y185    [get_cells -regexp -hier ".*ring_stage.0._inferred_i_13" ]
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X96Y185    [get_cells -regexp -hier ".*ring_stage.0._inferred_i_14" ]
set_property src_info {type:XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X96Y185    [get_cells -regexp -hier ".*ring_stage.0._inferred_i_15" ]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X96Y185    [get_cells -regexp -hier ".*ring_stage.0._inferred_i_16" ]
set_property src_info {type:XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X95Y183    [get_cells -regexp -hier ".*ring_stage.1._inferred_i_1" ]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X95Y183    [get_cells -regexp -hier ".*ring_stage.1._inferred_i_2" ]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X95Y183    [get_cells -regexp -hier ".*ring_stage.1._inferred_i_3" ]
set_property src_info {type:XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X95Y183    [get_cells -regexp -hier ".*ring_stage.1._inferred_i_4" ]
set_property src_info {type:XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X95Y183    [get_cells -regexp -hier ".*ring_stage.1._inferred_i_5" ]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X95Y183    [get_cells -regexp -hier ".*ring_stage.1._inferred_i_6" ]
set_property src_info {type:XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X95Y183    [get_cells -regexp -hier ".*ring_stage.1._inferred_i_7" ]
set_property src_info {type:XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X95Y183    [get_cells -regexp -hier ".*ring_stage.1._inferred_i_8" ]
set_property src_info {type:XDC file:1 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X96Y183    [get_cells -regexp -hier ".*ring_stage.1._inferred_i_9" ]
set_property src_info {type:XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X96Y183    [get_cells -regexp -hier ".*ring_stage.1._inferred_i_10" ]
set_property src_info {type:XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X96Y183    [get_cells -regexp -hier ".*ring_stage.1._inferred_i_11" ]
set_property src_info {type:XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X96Y183    [get_cells -regexp -hier ".*ring_stage.1._inferred_i_12" ]
set_property src_info {type:XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X96Y183    [get_cells -regexp -hier ".*ring_stage.1._inferred_i_13" ]
set_property src_info {type:XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X96Y183    [get_cells -regexp -hier ".*ring_stage.1._inferred_i_14" ]
set_property src_info {type:XDC file:1 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X96Y183    [get_cells -regexp -hier ".*ring_stage.1._inferred_i_15" ]
set_property src_info {type:XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X96Y183    [get_cells -regexp -hier ".*ring_stage.1._inferred_i_16" ]
