# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/edt/RNG/RNG.srcs/sources_1/ip/ring_counter_fifo/ring_counter_fifo.xci
# IP: The module: 'ring_counter_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/edt/RNG/RNG.gen/sources_1/ip/ring_counter_fifo/ring_counter_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'ring_counter_fifo'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/edt/RNG/RNG.gen/sources_1/ip/ring_counter_fifo/ring_counter_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'ring_counter_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/edt/RNG/RNG.gen/sources_1/ip/ring_counter_fifo/ring_counter_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ring_counter_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/edt/RNG/RNG.srcs/sources_1/ip/ring_counter_fifo/ring_counter_fifo.xci
# IP: The module: 'ring_counter_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/edt/RNG/RNG.gen/sources_1/ip/ring_counter_fifo/ring_counter_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'ring_counter_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/edt/RNG/RNG.gen/sources_1/ip/ring_counter_fifo/ring_counter_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'ring_counter_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/edt/RNG/RNG.gen/sources_1/ip/ring_counter_fifo/ring_counter_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ring_counter_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
