# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/edt/RNG/RNG.srcs/sources_1/ip/master_ring_pll_220m/master_ring_pll_220m.xci
# IP: The module: 'master_ring_pll_220m' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/edt/RNG/RNG.gen/sources_1/ip/master_ring_pll_220m/master_ring_pll_220m_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'master_ring_pll_220m'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/edt/RNG/RNG.gen/sources_1/ip/master_ring_pll_220m/master_ring_pll_220m.xdc
# XDC: The top module name and the constraint reference have the same name: 'master_ring_pll_220m'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/edt/RNG/RNG.gen/sources_1/ip/master_ring_pll_220m/master_ring_pll_220m_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'master_ring_pll_220m'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/edt/RNG/RNG.srcs/sources_1/ip/master_ring_pll_220m/master_ring_pll_220m.xci
# IP: The module: 'master_ring_pll_220m' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/edt/RNG/RNG.gen/sources_1/ip/master_ring_pll_220m/master_ring_pll_220m_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'master_ring_pll_220m'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/edt/RNG/RNG.gen/sources_1/ip/master_ring_pll_220m/master_ring_pll_220m.xdc
# XDC: The top module name and the constraint reference have the same name: 'master_ring_pll_220m'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/edt/RNG/RNG.gen/sources_1/ip/master_ring_pll_220m/master_ring_pll_220m_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'master_ring_pll_220m'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
