# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/edt/RNG/RNG.srcs/sources_1/ip/raw_sample_fifo/raw_sample_fifo.xci
# IP: The module: 'raw_sample_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/edt/RNG/RNG.gen/sources_1/ip/raw_sample_fifo/raw_sample_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'raw_sample_fifo'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/edt/RNG/RNG.gen/sources_1/ip/raw_sample_fifo/raw_sample_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'raw_sample_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/edt/RNG/RNG.gen/sources_1/ip/raw_sample_fifo/raw_sample_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'raw_sample_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/edt/RNG/RNG.srcs/sources_1/ip/raw_sample_fifo/raw_sample_fifo.xci
# IP: The module: 'raw_sample_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/edt/RNG/RNG.gen/sources_1/ip/raw_sample_fifo/raw_sample_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'raw_sample_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/edt/RNG/RNG.gen/sources_1/ip/raw_sample_fifo/raw_sample_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'raw_sample_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/edt/RNG/RNG.gen/sources_1/ip/raw_sample_fifo/raw_sample_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'raw_sample_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
